#!/usr/bin/env bash
#
# Generates src/syscall_names.h from the kernel's unistd_64.h header.
# Re-run this if you ever need to refresh the table (new kernel, etc).
#
# Usage: ./scripts/gen_syscall_table.sh > src/syscall_names.h

set -euo pipefail

HEADER="/usr/include/x86_64-linux-gnu/asm/unistd_64.h"

if [ ! -f "$HEADER" ]; then
    echo "error: $HEADER not found (are you on x86-64 Linux?)" >&2
    exit 1
fi

MAX=$(awk '/^#define __NR_/ { if ($3+0 > m) m = $3+0 } END { print m }' "$HEADER")

echo "/* Auto-generated by scripts/gen_syscall_table.sh — do not edit by hand. */"
echo "#ifndef SYSCALL_NAMES_H"
echo "#define SYSCALL_NAMES_H"
echo
echo "#define SYSCALL_TABLE_MAX $MAX"
echo
echo "static const char *syscall_names[SYSCALL_TABLE_MAX + 1] = {"

awk -v max="$MAX" '
/^#define __NR_/ {
    name = $2
    sub(/^__NR_/, "", name)
    num = $3 + 0
    names[num] = name
}
END {
    for (i = 0; i <= max; i++) {
        if (i in names)
            printf "    [%d] = \"%s\",\n", i, names[i]
    }
}
' "$HEADER"

echo "};"
echo
echo "static inline const char *syscall_name(long nr) {"
echo "    if (nr < 0 || nr > SYSCALL_TABLE_MAX || syscall_names[nr] == NULL)"
echo "        return \"unknown\";"
echo "    return syscall_names[nr];"
echo "}"
echo
echo "#endif /* SYSCALL_NAMES_H */"
