#!/usr/bin/env bash
#
# Generates src/syscall_names.h from the kernel's syscall header for
# the current architecture. Re-run this if you ever need to refresh
# the table (new kernel, different machine, etc).
#
# Usage: ./scripts/gen_syscall_table.sh > src/syscall_names.h

set -euo pipefail

ARCH=$(uname -m)

case "$ARCH" in
    x86_64)
        INCLUDE_HEADER="asm/unistd_64.h"
        ;;
    aarch64|arm64)
        # aarch64 doesn't have its own numbering — asm/unistd.h just
        # pulls in the generic table.
        INCLUDE_HEADER="asm/unistd.h"
        ;;
    *)
        echo "error: unsupported architecture $ARCH" >&2
        exit 1
        ;;
esac

# Ask gcc to preprocess the header and dump every #define — this
# avoids hardcoding an include path, which differs depending on how
# the toolchain/headers got installed (native package, cross-compiler
# sysroot, distro, etc). gcc always knows where its own headers are.
DEFS=$(gcc -E -dM -include "$INCLUDE_HEADER" -x c /dev/null 2>/dev/null) || {
    echo "error: gcc couldn't find/preprocess <$INCLUDE_HEADER> — is libc6-dev installed?" >&2
    exit 1
}

if [ -z "$DEFS" ]; then
    echo "error: no macros produced — something's wrong with the toolchain" >&2
    exit 1
fi

# Some syscalls (mmap, stat, fstat, ...) aren't defined as a plain
# number — they're defined as __NR_mmap -> __NR3264_mmap -> 222, a
# level of indirection used to share numbers between 32 and 64-bit
# time_t builds. Resolving that chain is easier in a real language
# than in awk regex soup, hence python here instead.
echo "$DEFS" | python3 -c '
import sys, re

raw = {}  # macro name -> its right-hand side (number or another macro name)
for line in sys.stdin:
    m = re.match(r"#define\s+(__NR\w*)\s+(\S+)", line)
    if m:
        raw[m.group(1)] = m.group(2)

def resolve(name, depth=0):
    val = raw.get(name)
    if val is None or depth > 5:
        return None
    if val.isdigit():
        return int(val)
    return resolve(val, depth + 1)  # value is another macro name — follow it

names = {}  # syscall number -> chosen name (first one wins)
for macro in raw:
    if not macro.startswith("__NR_"):
        continue
    short = macro[len("__NR_"):]
    if short == "syscalls":
        continue
    num = resolve(macro)
    if num is not None and num not in names:
        names[num] = short

max_num = max(names) if names else 0

print("/* Auto-generated by scripts/gen_syscall_table.sh — do not edit by hand. */")
print("#ifndef SYSCALL_NAMES_H")
print("#define SYSCALL_NAMES_H")
print()
print(f"#define SYSCALL_TABLE_MAX {max_num}")
print()
print("static const char *syscall_names[SYSCALL_TABLE_MAX + 1] = {")
for i in range(max_num + 1):
    if i in names:
        print(f"    [{i}] = \"{names[i]}\",")
print("};")
print()
print("static inline const char *syscall_name(long nr) {")
print("    if (nr < 0 || nr > SYSCALL_TABLE_MAX || syscall_names[nr] == NULL)")
print("        return \"unknown\";")
print("    return syscall_names[nr];")
print("}")
print()
print("#endif /* SYSCALL_NAMES_H */")
'
